### ISSUE TITLE
自動生成されたファイルが本当に必要なのか再考しよう

### ISSUE THREAD

**Issue by norotime** [horisakis/savoriter#4]
https://github.com/horisakis/savoriter/blob/ebf03d5a2863b64bc982ce1d68b330d9346376ac/app/assets/stylesheets/scaffolds.scss#L1

**Comment by horisakis** [comment]
現状はこのファイルの内容を使って動いていますが、一部だけ別のファイルに値を写して使用したり、全く使用せず削除しても良かったと思います。今後の参考とします。
